<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-07T14:39:10 IST" name="Default suite" finished-at="2022-04-07T14:39:24 IST" duration-ms="13827">
    <groups>
    </groups>
    <test started-at="2022-04-07T14:39:10 IST" name="Default test" finished-at="2022-04-07T14:39:24 IST" duration-ms="13827">
      <class name="project_2.Output_Class">
        <test-method is-config="true" signature="openbrowser()[pri:0, instance:project_2.Output_Class@4f18837a]" started-at="2022-04-07T14:39:10 IST" name="openbrowser" finished-at="2022-04-07T14:39:14 IST" duration-ms="3372" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openbrowser -->
        <test-method is-config="true" signature="loginAPP()[pri:0, instance:project_2.Output_Class@4f18837a]" started-at="2022-04-07T14:39:14 IST" name="loginAPP" finished-at="2022-04-07T14:39:18 IST" duration-ms="4300" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAPP -->
        <test-method signature="verifyuser()[pri:0, instance:project_2.Output_Class@4f18837a]" started-at="2022-04-07T14:39:18 IST" name="verifyuser" finished-at="2022-04-07T14:39:19 IST" duration-ms="726" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Pass Case expected [812073] but found [THM944]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Pass Case expected [812073] but found [THM944]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at project_2.Output_Class.verifyuser(Output_Class.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyuser -->
        <test-method is-config="true" signature="LogoutFromApp(org.testng.ITestResult)[pri:0, instance:project_2.Output_Class@4f18837a]" started-at="2022-04-07T14:39:19 IST" name="LogoutFromApp" finished-at="2022-04-07T14:39:19 IST" duration-ms="233" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyuser status=FAILURE method=Output_Class.verifyuser()[pri:0, instance:project_2.Output_Class@4f18837a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogoutFromApp -->
        <test-method is-config="true" signature="closebrowser()[pri:0, instance:project_2.Output_Class@4f18837a]" started-at="2022-04-07T14:39:19 IST" name="closebrowser" finished-at="2022-04-07T14:39:24 IST" duration-ms="5164" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closebrowser -->
      </class> <!-- project_2.Output_Class -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
